---
# Add and remove users to all nodes
# ansible-playbook -i /ansible/inventory /ansible/playbooks/example-04.yml
- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Include user vars
      include_vars:
        file: "{{ playbook_dir }}/vars/users.yml"
        name: users

    - name: Create users
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        shell: /bin/bash
        password: "{{ (item.name + '1234') | password_hash('sha512') }}"
        update_password: on_create
        state: present
      with_items: "{{ users.users }}"
    
    - name: Remove users
      user:
        name: "{{ item.name }}"
        state: absent
        remove: yes
      with_items: "{{ users.users }}"