---
# Print message to the terminal
# ansible-playbook -i /ansible/inventory /ansible/playbooks/example-01.yml
- hosts: all
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World